name: Documentation
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: >
            cd docs;
            DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24'
            julia --color=yes make.jl