name: Format suggestions
on:
  pull_request:
    types: [labeled]
  pull_request_target:
    types: [labeled]
jobs:
  code-style:
    runs-on: ubuntu-latest
    if: (( github.event.pull_request.head.repo.fork == false && github.event_name == 'pull_request' ) || ( github.event.pull_request.head.repo.fork == true && github.event_name == 'pull_request_target' )) && contains(github.event.pull_request.labels.*.name, 'ok to format')
    permissions:
      pull-requests: write
    steps:
      - uses: julia-actions/julia-format@v2
